// Services - arrays of strings
export const STUDIO_A_SERVICES = [
  'Recording Session',
  'Mixing',
  'Mastering',
  'Vocal Booth',
]

export const STUDIO_B_SERVICES = [
  'Recording Session',
  'Podcast Recording',
  'Voice Over',
  'Band Rehearsal',
]

export const SERVICE_PRICING: Record<string, number> = {
  'Recording Session': 150,
  'Mixing': 250,
  'Mastering': 200,
  'Vocal Booth': 100,
  'Podcast Recording': 100,
  'Voice Over': 75,
  'Band Rehearsal': 180,
}

// Task stages for kanban board
export const TASK_STAGES = ['To Do', 'In Progress', 'Review', 'Done'] as const
export type TaskStage = typeof TASK_STAGES[number]

// Employees
export const MOCK_EMPLOYEES = [
  { id: 'e1', name: 'Alex Johnson', role: 'Sound Engineer', studio: 'A', available: true },
  { id: 'e2', name: 'Jamie Lee', role: 'Producer', studio: 'A', available: true },
  { id: 'e3', name: 'Morgan Smith', role: 'Mixing Engineer', studio: 'B', available: false },
  { id: 'e4', name: 'Taylor Brown', role: 'Mastering Engineer', studio: 'B', available: true },
]

// Clients
export const MOCK_CLIENTS = [
  {
    id: 'c1',
    name: 'The Midnight Echoes',
    email: 'contact@midnightechoes.com',
    phone: '555-0101',
    ig: '@midnightechoes',
    totalSessions: 12,
    total_sessions: 12,
    totalSpend: 3200,
    total_spend: 3200,
    lastVisit: '2026-04-10',
    last_visit: '2026-04-10',
  },
  {
    id: 'c2',
    name: 'Sarah Connelly',
    email: 'sarah@example.com',
    phone: '555-0102',
    ig: '@sarahconnelly',
    totalSessions: 5,
    total_sessions: 5,
    totalSpend: 950,
    total_spend: 950,
    lastVisit: '2026-04-15',
    last_visit: '2026-04-15',
  },
  {
    id: 'c3',
    name: 'Neon Wave Band',
    email: 'neonwave@example.com',
    phone: '555-0103',
    ig: '@neonwaveband',
    totalSessions: 8,
    total_sessions: 8,
    totalSpend: 2100,
    total_spend: 2100,
    lastVisit: '2026-04-18',
    last_visit: '2026-04-18',
  },
  {
    id: 'c4',
    name: 'DJ Pulse',
    email: 'djpulse@example.com',
    phone: '555-0104',
    ig: '@djpulse',
    totalSessions: 20,
    total_sessions: 20,
    totalSpend: 5500,
    total_spend: 5500,
    lastVisit: '2026-04-20',
    last_visit: '2026-04-20',
  },
]

// Sessions — includes both camelCase and snake_case, plus nested `clients` for Supabase-style joins
export const MOCK_SESSIONS = [
  {
    id: 's1',
    client_id: 'c1',
    clientId: 'c1',
    client_name: 'The Midnight Echoes',
    clientName: 'The Midnight Echoes',
    clients: { id: 'c1', name: 'The Midnight Echoes', email: 'contact@midnightechoes.com' },
    service: 'Recording Session',
    studio: 'A',
    engineer: 'Alex Johnson',
    date: '2026-04-24',
    start_time: '2026-04-24T10:00:00',
    end_time: '2026-04-24T11:00:00',
    startTime: '10:00',
    endTime: '11:00',
    duration: 60,
    price: 150,
    status: 'confirmed',
    payment_status: 'paid',
    paymentStatus: 'paid',
  },
  {
    id: 's2',
    client_id: 'c2',
    clientId: 'c2',
    client_name: 'Sarah Connelly',
    clientName: 'Sarah Connelly',
    clients: { id: 'c2', name: 'Sarah Connelly', email: 'sarah@example.com' },
    service: 'Vocal Booth',
    studio: 'A',
    engineer: 'Jamie Lee',
    date: '2026-04-24',
    start_time: '2026-04-24T13:00:00',
    end_time: '2026-04-24T14:00:00',
    startTime: '13:00',
    endTime: '14:00',
    duration: 60,
    price: 100,
    status: 'confirmed',
    payment_status: 'pending',
    paymentStatus: 'pending',
  },
  {
    id: 's3',
    client_id: 'c3',
    clientId: 'c3',
    client_name: 'Neon Wave Band',
    clientName: 'Neon Wave Band',
    clients: { id: 'c3', name: 'Neon Wave Band', email: 'neonwave@example.com' },
    service: 'Band Rehearsal',
    studio: 'B',
    engineer: 'Taylor Brown',
    date: '2026-04-25',
    start_time: '2026-04-25T14:00:00',
    end_time: '2026-04-25T16:00:00',
    startTime: '14:00',
    endTime: '16:00',
    duration: 120,
    price: 180,
    status: 'confirmed',
    payment_status: 'paid',
    paymentStatus: 'paid',
  },
  {
    id: 's4',
    client_id: 'c4',
    clientId: 'c4',
    client_name: 'DJ Pulse',
    clientName: 'DJ Pulse',
    clients: { id: 'c4', name: 'DJ Pulse', email: 'djpulse@example.com' },
    service: 'Mixing',
    studio: 'A',
    engineer: 'Alex Johnson',
    date: '2026-04-26',
    start_time: '2026-04-26T11:00:00',
    end_time: '2026-04-26T13:00:00',
    startTime: '11:00',
    endTime: '13:00',
    duration: 120,
    price: 250,
    status: 'pending',
    payment_status: 'unpaid',
    paymentStatus: 'unpaid',
  },
  {
    id: 's5',
    client_id: 'c1',
    clientId: 'c1',
    client_name: 'The Midnight Echoes',
    clientName: 'The Midnight Echoes',
    clients: { id: 'c1', name: 'The Midnight Echoes', email: 'contact@midnightechoes.com' },
    service: 'Mastering',
    studio: 'B',
    engineer: 'Morgan Smith',
    date: '2026-04-27',
    start_time: '2026-04-27T15:00:00',
    end_time: '2026-04-27T16:30:00',
    startTime: '15:00',
    endTime: '16:30',
    duration: 90,
    price: 200,
    status: 'confirmed',
    payment_status: 'paid',
    paymentStatus: 'paid',
  },
]

// Payment statuses
export const PAYMENT_STATUSES = ['paid', 'pending', 'unpaid', 'refunded'] as const
export type PaymentStatus = typeof PAYMENT_STATUSES[number]
